//! Standard MCP `ServerHandler` surface for the Capability Gateway.

use a3s_use_core::ResourceRef;
use rmcp::handler::server::tool::ToolCallContext;
use rmcp::model::{
    CallToolRequestParam, CallToolResult, GetPromptRequestParam, GetPromptResult, Implementation,
    ListPromptsResult, ListResourcesResult, ListToolsResult, PaginatedRequestParam,
    ReadResourceRequestParam, ReadResourceResult, ServerCapabilities, ServerInfo,
};
use rmcp::ServerHandler;
use serde_json::Value;

use super::super::protocol::{
    cancellation_error, content_admission, descriptor_is_visible, discovery_page,
    run_until_cancelled, validate_prompt_arguments, validate_prompt_result,
    validate_resource_contents,
};
use super::super::CapabilityGatewayInvocationFailure;
use super::CapabilityGatewayMcpServer;

impl ServerHandler for CapabilityGatewayMcpServer {
    fn get_info(&self) -> ServerInfo {
        let capabilities = ServerCapabilities {
            // The Gateway implements all three standard discovery surfaces
            // and may gain a surface on the next immutable publication. Keep
            // the capabilities advertised even when this generation is empty,
            // and explicitly opt into standard list-change notifications.
            prompts: Some(rmcp::model::PromptsCapability {
                list_changed: Some(true),
            }),
            resources: Some(rmcp::model::ResourcesCapability {
                subscribe: None,
                list_changed: Some(true),
            }),
            tools: Some(rmcp::model::ToolsCapability {
                list_changed: Some(true),
            }),
            ..Default::default()
        };
        ServerInfo {
            capabilities,
            server_info: Implementation {
                name: "a3s-use-capability-gateway".to_owned(),
                title: Some("A3S Use Capability Gateway".to_owned()),
                version: env!("CARGO_PKG_VERSION").to_owned(),
                icons: None,
                website_url: Some("https://github.com/A3S-Lab/Use".to_owned()),
            },
            instructions: Some(
                "The catalog is immutable and generation-bound. Tool calls are resolved by the host from opaque references; client-supplied paths, package roots, endpoints, and credentials are not accepted."
                    .to_owned(),
            ),
            ..Default::default()
        }
    }

    /// Dispatch Tool calls through the frozen router. This is the small
    /// portion normally generated by rmcp's `tool_handler` macro; it remains
    /// explicit here because the generated `list_tools` implementation is
    /// unbounded and iterates a hash map in an unstable order.
    async fn call_tool(
        &self,
        request: CallToolRequestParam,
        request_context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        let tool_context = ToolCallContext::new(self, request, request_context);
        self.tool_router.call(tool_context).await
    }

    /// List Tools in stable name order with the same bounded, projection-bound
    /// cursor contract used by Resources and Prompts. `ToolRouter` stores
    /// routes in a HashMap, so sorting is required for a cursor to remain
    /// meaningful across calls.
    async fn list_tools(
        &self,
        request: Option<PaginatedRequestParam>,
        request_context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> Result<ListToolsResult, rmcp::ErrorData> {
        let context = self.request_context(&request_context)?;
        let view = self
            .discovery_view_with_cancellation(&context, &request_context.ct)
            .await?;
        let mut tools = self.tool_router.list_all();
        tools.retain(|tool| {
            let name: &str = tool.name.as_ref();
            self.tools
                .get(name)
                .is_some_and(|route| descriptor_is_visible(&view, route.descriptor_index))
        });
        tools.sort_by(|left, right| left.name.cmp(&right.name));
        let fingerprint = self.discovery_cursor_fingerprint("tools", &view);
        let (start, end, next_cursor) = discovery_page(
            request.and_then(|request| request.cursor),
            "tools",
            &fingerprint,
            tools.len(),
        )?;
        let mut result = ListToolsResult::with_all_items(
            tools.into_iter().skip(start).take(end - start).collect(),
        );
        result.next_cursor = next_cursor;
        Ok(result)
    }

    async fn list_resources(
        &self,
        request: Option<PaginatedRequestParam>,
        request_context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> Result<ListResourcesResult, rmcp::ErrorData> {
        let context = self.request_context(&request_context)?;
        let view = self
            .discovery_view_with_cancellation(&context, &request_context.ct)
            .await?;
        let resources = self
            .resources
            .values()
            .filter(|route| descriptor_is_visible(&view, route.descriptor_index))
            .map(|route| route.resource.clone())
            .collect::<Vec<_>>();
        let fingerprint = self.discovery_cursor_fingerprint("resources", &view);
        let (start, end, next_cursor) = discovery_page(
            request.and_then(|request| request.cursor),
            "resources",
            &fingerprint,
            resources.len(),
        )?;
        let mut result = ListResourcesResult::with_all_items(
            resources
                .into_iter()
                .skip(start)
                .take(end - start)
                .collect(),
        );
        result.next_cursor = next_cursor;
        Ok(result)
    }

    async fn list_prompts(
        &self,
        request: Option<PaginatedRequestParam>,
        request_context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> Result<ListPromptsResult, rmcp::ErrorData> {
        let context = self.request_context(&request_context)?;
        let view = self
            .discovery_view_with_cancellation(&context, &request_context.ct)
            .await?;
        let prompts = self
            .prompts
            .values()
            .filter(|route| descriptor_is_visible(&view, route.descriptor_index))
            .map(|route| route.prompt.clone())
            .collect::<Vec<_>>();
        let fingerprint = self.discovery_cursor_fingerprint("prompts", &view);
        let (start, end, next_cursor) = discovery_page(
            request.and_then(|request| request.cursor),
            "prompts",
            &fingerprint,
            prompts.len(),
        )?;
        let mut result = ListPromptsResult::with_all_items(
            prompts.into_iter().skip(start).take(end - start).collect(),
        );
        result.next_cursor = next_cursor;
        Ok(result)
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParam,
        request_context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> Result<ReadResourceResult, rmcp::ErrorData> {
        let context = self.request_context(&request_context)?;
        let resource_ref = ResourceRef::parse(request.uri.clone()).map_err(|_| {
            rmcp::ErrorData::invalid_params(
                "The requested Capability Gateway resource URI is invalid.",
                None,
            )
        })?;
        let route = self.resources.get(resource_ref.as_str()).ok_or_else(|| {
            rmcp::ErrorData::resource_not_found(
                "The requested Capability Gateway resource is not published.",
                None,
            )
        })?;
        let view = self
            .discovery_view_with_cancellation(&context, &request_context.ct)
            .await?;
        if !descriptor_is_visible(&view, route.descriptor_index) {
            return Err(rmcp::ErrorData::resource_not_found(
                "The requested Capability Gateway resource is not published.",
                None,
            ));
        }
        let _permit = content_admission(&self.admission)?;
        let descriptor = self
            .catalog
            .descriptors()
            .get(route.descriptor_index)
            .ok_or_else(|| {
                rmcp::ErrorData::internal_error(
                    "Capability Gateway route index is inconsistent with its catalog.",
                    None,
                )
            })?;
        let contents = match run_until_cancelled(
            &request_context.ct,
            self.provider
                .authorize_and_read_resource(descriptor, &context),
        )
        .await
        {
            None => return Err(cancellation_error()),
            Some(result) => match result {
                Ok(contents) => contents,
                Err(CapabilityGatewayInvocationFailure::Authorization(_)) => {
                    return Err(rmcp::ErrorData::invalid_request(
                        "The Capability Gateway denied this resource request.",
                        None,
                    ));
                }
                Err(CapabilityGatewayInvocationFailure::Invocation(_)) => {
                    return Err(rmcp::ErrorData::internal_error(
                        "The Capability Gateway could not read this resource.",
                        None,
                    ));
                }
            },
        };
        validate_resource_contents(&request.uri, &contents).map_err(|_| {
            rmcp::ErrorData::internal_error(
                "The Capability Gateway resource provider returned an invalid result.",
                None,
            )
        })?;
        Ok(ReadResourceResult { contents })
    }

    async fn get_prompt(
        &self,
        request: GetPromptRequestParam,
        request_context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> Result<GetPromptResult, rmcp::ErrorData> {
        let context = self.request_context(&request_context)?;
        let route = self.prompts.get(&request.name).ok_or_else(|| {
            rmcp::ErrorData::invalid_params(
                "The requested Capability Gateway prompt is not published.",
                None,
            )
        })?;
        let view = self
            .discovery_view_with_cancellation(&context, &request_context.ct)
            .await?;
        if !descriptor_is_visible(&view, route.descriptor_index) {
            return Err(rmcp::ErrorData::invalid_params(
                "The requested Capability Gateway prompt is not published.",
                None,
            ));
        }
        let arguments = Value::Object(request.arguments.unwrap_or_default());
        validate_prompt_arguments(&arguments, &route.arguments).map_err(|_| {
            rmcp::ErrorData::invalid_params(
                "The Capability Gateway prompt arguments are invalid.",
                None,
            )
        })?;
        let _permit = content_admission(&self.admission)?;
        let descriptor = self
            .catalog
            .descriptors()
            .get(route.descriptor_index)
            .ok_or_else(|| {
                rmcp::ErrorData::internal_error(
                    "Capability Gateway route index is inconsistent with its catalog.",
                    None,
                )
            })?;
        let result = match run_until_cancelled(
            &request_context.ct,
            self.provider
                .authorize_and_get_prompt(descriptor, arguments, &context),
        )
        .await
        {
            None => return Err(cancellation_error()),
            Some(result) => match result {
                Ok(result) => result,
                Err(CapabilityGatewayInvocationFailure::Authorization(_)) => {
                    return Err(rmcp::ErrorData::invalid_request(
                        "The Capability Gateway denied this prompt request.",
                        None,
                    ));
                }
                Err(CapabilityGatewayInvocationFailure::Invocation(_)) => {
                    return Err(rmcp::ErrorData::internal_error(
                        "The Capability Gateway could not generate this prompt.",
                        None,
                    ));
                }
            },
        };
        let visible_resource_uris = self.visible_resource_uris(&view);
        validate_prompt_result(&result, &visible_resource_uris).map_err(|_| {
            rmcp::ErrorData::internal_error(
                "The Capability Gateway prompt provider returned an invalid result.",
                None,
            )
        })?;
        Ok(result)
    }

    async fn on_initialized(&self, context: rmcp::service::NotificationContext<rmcp::RoleServer>) {
        let _ = self.notification_hub.register(context.peer).await;
    }
}
