use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

use a3s_use_core::{
    ArtifactRef, CapabilityConsumerExtension, CapabilityConsumerNegotiation, CapabilityDescriptor,
    CapabilityDescriptorKind, CapabilityGatewayCatalog, CapabilityPromptArgument,
    CapabilityPublicationEvidence, CapabilityToolAnnotations, EndpointRef, InstallationId,
    InstallationKind, InvocationRef, PluginPackageId, PluginSurfaceKind, PluginSurfaceRef,
    ResourceRef, CAPABILITY_DESCRIPTOR_SCHEMA_V1,
};
use rmcp::model::{
    CallToolRequestParam, GetPromptRequestParam, GetPromptResult, PromptMessage, PromptMessageRole,
    ReadResourceRequestParam, ResourceContents,
};
use rmcp::transport::streamable_http_client::{
    StreamableHttpClientTransport, StreamableHttpClientTransportConfig,
};
use rmcp::{ClientHandler, ServiceExt};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio_util::sync::CancellationToken;

use crate::capability_registry::{
    CapabilityPackageGeneration, CapabilityRegistry, CapabilitySnapshotLease,
    CAPABILITY_SNAPSHOT_CURSOR_SCHEMA,
};

use super::*;

#[derive(Debug, Default)]
struct RecordingProvider {
    authorizations: Mutex<Vec<CapabilityGatewayRequestContext>>,
    calls: Mutex<Vec<(InvocationRef, Value, CapabilityGatewayRequestContext)>>,
}

#[derive(Debug, Default)]
struct RecordingProviderWithoutContent;

#[async_trait]
impl CapabilityGatewayInvocationProvider for RecordingProviderWithoutContent {
    async fn authorize(
        &self,
        _descriptor: &CapabilityDescriptor,
        _arguments: &Value,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<()> {
        Ok(())
    }

    async fn invoke(
        &self,
        _descriptor: &CapabilityDescriptor,
        _arguments: Value,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<Value> {
        Ok(serde_json::json!({ "ok": true }))
    }
}

#[async_trait]
impl CapabilityGatewayInvocationProvider for RecordingProvider {
    async fn authorize(
        &self,
        _descriptor: &CapabilityDescriptor,
        _arguments: &Value,
        context: &CapabilityGatewayRequestContext,
    ) -> UseResult<()> {
        self.authorizations
            .lock()
            .map_err(|_| UseError::new("test.provider_poisoned", "Provider lock poisoned."))?
            .push(context.clone());
        Ok(())
    }

    async fn invoke(
        &self,
        descriptor: &CapabilityDescriptor,
        arguments: Value,
        context: &CapabilityGatewayRequestContext,
    ) -> UseResult<Value> {
        self.calls
            .lock()
            .map_err(|_| UseError::new("test.provider_poisoned", "Provider lock poisoned."))?
            .push((
                descriptor.invocation_ref.clone(),
                arguments.clone(),
                context.clone(),
            ));
        Ok(serde_json::json!({ "ok": true, "arguments": arguments }))
    }

    async fn read_resource(
        &self,
        descriptor: &CapabilityDescriptor,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<Vec<ResourceContents>> {
        let uri = descriptor
            .resource_uri()
            .ok_or_else(|| UseError::new("test.not_resource", "Expected a resource descriptor."))?;
        Ok(vec![ResourceContents::text(
            "verified resource contents",
            uri.as_str(),
        )])
    }

    async fn get_prompt(
        &self,
        _descriptor: &CapabilityDescriptor,
        arguments: Value,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<GetPromptResult> {
        Ok(GetPromptResult {
            description: Some("Generated by the verified provider.".to_owned()),
            messages: vec![PromptMessage::new_text(
                PromptMessageRole::User,
                format!("Research topic: {}", arguments["topic"]),
            )],
        })
    }
}

#[derive(Debug, Default)]
struct InvalidOutputProvider;

#[async_trait]
impl CapabilityGatewayInvocationProvider for InvalidOutputProvider {
    async fn authorize(
        &self,
        _descriptor: &CapabilityDescriptor,
        _arguments: &Value,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<()> {
        Ok(())
    }

    async fn invoke(
        &self,
        _descriptor: &CapabilityDescriptor,
        _arguments: Value,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<Value> {
        Ok(serde_json::json!({
            "ok": "not-a-boolean",
            "arguments": {}
        }))
    }
}

#[derive(Debug, Default)]
struct FailingProvider;

#[async_trait]
impl CapabilityGatewayInvocationProvider for FailingProvider {
    async fn authorize(
        &self,
        _descriptor: &CapabilityDescriptor,
        _arguments: &Value,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<()> {
        Ok(())
    }

    async fn invoke(
        &self,
        _descriptor: &CapabilityDescriptor,
        _arguments: Value,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<Value> {
        Err(UseError::new(
            "provider.internal_secret",
            "private token /srv/a3s/secrets/token",
        )
        .with_suggestion("read /srv/a3s/secrets/token")
        .with_detail("path", "/srv/a3s/secrets/token"))
    }
}

#[derive(Debug, Default)]
struct DenyingProvider {
    calls: Mutex<Vec<InvocationRef>>,
}

#[async_trait]
impl CapabilityGatewayInvocationProvider for DenyingProvider {
    async fn authorize(
        &self,
        _descriptor: &CapabilityDescriptor,
        _arguments: &Value,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<()> {
        Err(UseError::new(
            "host.private_authorization_reason",
            "private policy details must not cross the Gateway boundary",
        ))
    }

    async fn invoke(
        &self,
        descriptor: &CapabilityDescriptor,
        _arguments: Value,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<Value> {
        self.calls
            .lock()
            .map_err(|_| UseError::new("test.provider_poisoned", "Provider lock poisoned."))?
            .push(descriptor.invocation_ref.clone());
        Ok(serde_json::json!({ "ok": true }))
    }
}

#[derive(Debug, Default)]
struct PrincipalPolicyProvider {
    calls: Mutex<Vec<CapabilityGatewayRequestContext>>,
}

#[derive(Debug)]
struct LeaseProbeResolver {
    expected: InvocationRef,
    resolves: AtomicUsize,
    active: Arc<AtomicUsize>,
    completed: Arc<AtomicUsize>,
}

struct LeaseProbe {
    active: Arc<AtomicUsize>,
    completed: Arc<AtomicUsize>,
}

#[derive(Debug, Default)]
struct NoopFactory;

#[async_trait]
impl CapabilityGatewayInvocationFactory for NoopFactory {
    async fn open(
        &self,
        _descriptor: &CapabilityDescriptor,
        _context: &CapabilityGatewayRequestContext,
        _snapshot: &CapabilitySnapshotLease,
    ) -> UseResult<Box<dyn CapabilityGatewayInvocation>> {
        Err(UseError::new(
            "test.factory_not_called",
            "The test factory must not be called.",
        ))
    }
}

impl Drop for LeaseProbe {
    fn drop(&mut self) {
        self.active.fetch_sub(1, Ordering::SeqCst);
    }
}

#[async_trait]
impl CapabilityGatewayInvocation for LeaseProbe {
    async fn authorize(
        &self,
        _arguments: &Value,
        context: &CapabilityGatewayRequestContext,
    ) -> UseResult<()> {
        assert_eq!(context.transport(), CapabilityGatewayTransport::Stdio);
        Ok(())
    }

    async fn invoke(
        &self,
        arguments: Value,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<Value> {
        assert_eq!(self.active.load(Ordering::SeqCst), 1);
        self.completed.fetch_add(1, Ordering::SeqCst);
        Ok(arguments)
    }
}

#[async_trait]
impl CapabilityGatewayInvocationResolver for LeaseProbeResolver {
    async fn resolve(
        &self,
        _descriptor: &CapabilityDescriptor,
        _context: &CapabilityGatewayRequestContext,
    ) -> UseResult<CapabilityGatewayInvocationLease> {
        self.resolves.fetch_add(1, Ordering::SeqCst);
        self.active.fetch_add(1, Ordering::SeqCst);
        Ok(CapabilityGatewayInvocationLease::new(
            self.expected.clone(),
            Box::new(LeaseProbe {
                active: Arc::clone(&self.active),
                completed: Arc::clone(&self.completed),
            }),
        ))
    }
}

#[async_trait]
impl CapabilityGatewayInvocationProvider for PrincipalPolicyProvider {
    async fn authorize(
        &self,
        _descriptor: &CapabilityDescriptor,
        _arguments: &Value,
        context: &CapabilityGatewayRequestContext,
    ) -> UseResult<()> {
        if context.principal().map(CapabilityGatewayPrincipal::as_str) == Some("agent/allowed") {
            Ok(())
        } else {
            Err(UseError::new(
                "host.principal_not_allowed",
                "The authenticated principal is not allowed for this capability.",
            ))
        }
    }

    async fn invoke(
        &self,
        _descriptor: &CapabilityDescriptor,
        _arguments: Value,
        context: &CapabilityGatewayRequestContext,
    ) -> UseResult<Value> {
        self.calls
            .lock()
            .map_err(|_| UseError::new("test.provider_poisoned", "Provider lock poisoned."))?
            .push(context.clone());
        Ok(serde_json::json!({ "ok": true }))
    }
}

#[derive(Debug, Clone, Copy, Default)]
struct TestClient;

impl ClientHandler for TestClient {}

#[test]
fn gateway_admission_is_bounded_and_shared() {
    let limits = CapabilityGatewayLimits::new(1, 2, Duration::from_secs(60)).unwrap();
    let admission = GatewayAdmission::new(limits).unwrap();
    let permit = admission.try_acquire().expect("first call is admitted");
    assert_eq!(
        admission.try_acquire().unwrap_err(),
        AdmissionFailure::InFlight
    );
    drop(permit);
    let permit = admission.try_acquire().expect("permit is released");
    drop(permit);
    assert_eq!(
        admission.try_acquire().unwrap_err(),
        AdmissionFailure::RateLimited
    );
}

#[test]
fn gateway_retains_the_explicit_consumer_negotiation() {
    let negotiation = CapabilityConsumerNegotiation::negotiate(
        a3s_use_core::CapabilityConsumerProfile::a3s([
            CapabilityConsumerExtension::Flow,
            CapabilityConsumerExtension::Ui,
        ])
        .unwrap(),
        [
            CapabilityConsumerExtension::Flow,
            CapabilityConsumerExtension::Knowledge,
            CapabilityConsumerExtension::Ui,
        ],
    )
    .unwrap();
    let server = CapabilityGatewayMcpServer::with_consumer_negotiation(
        test_catalog(test_descriptor()),
        Arc::new(RecordingProvider::default()),
        negotiation.clone(),
    )
    .unwrap();

    assert_eq!(server.consumer_negotiation(), &negotiation);
    assert_eq!(server.consumer_profile(), negotiation.profile());
    assert!(server
        .consumer_negotiation()
        .accepts(CapabilityConsumerExtension::Flow));
    assert!(!server
        .consumer_negotiation()
        .accepts(CapabilityConsumerExtension::Knowledge));
    assert_eq!(
        server.clone().consumer_negotiation(),
        &negotiation,
        "cloning a Gateway must not drop the negotiated profile"
    );
}

#[test]
fn gateway_limits_and_http_credentials_fail_closed() {
    assert!(CapabilityGatewayLimits::new(0, 1, Duration::from_secs(1)).is_err());
    assert!(CapabilityGatewayLimits::new(1, 1, Duration::ZERO).is_err());
    assert!(CapabilityGatewayLimits::new(1, 1, Duration::from_secs(60 * 60 + 1)).is_err());
    assert!(CapabilityGatewayHttpConfig::new("bad token").is_err());
    assert!(CapabilityGatewayHttpConfig::new("bad\n-token").is_err());
    assert!(CapabilityGatewayPrincipal::parse("").is_err());
    assert!(CapabilityGatewayPrincipal::parse("agent principal").is_err());

    let config =
        CapabilityGatewayHttpConfig::for_principal("secret-token", "agent/codex@workspace-01")
            .unwrap()
            .with_allowed_origin("https://agent.example")
            .unwrap();
    let debug = format!("{config:?}");
    assert!(debug.contains("[redacted]"));
    assert!(debug.contains("agent/codex@workspace-01"));
    assert!(!debug.contains("secret-token"));
    assert!(CapabilityGatewayHttpConfig::new("secret-token")
        .unwrap()
        .with_allowed_origin("https://agent example")
        .is_err());

    assert!(CapabilityGatewayHttpConfig::for_principals(Vec::<(String, String)>::new()).is_err());
    assert!(CapabilityGatewayHttpConfig::for_principals(vec![
        ("duplicate-token", "agent/one"),
        ("duplicate-token", "agent/two"),
    ])
    .is_err());
    assert!(
        CapabilityGatewayHttpConfig::for_principals(vec![("bad token", "agent/invalid",)]).is_err()
    );
    let too_many = (0..65)
        .map(|index| (format!("token-{index}"), format!("agent/{index}")))
        .collect::<Vec<_>>();
    assert!(CapabilityGatewayHttpConfig::for_principals(too_many).is_err());
    assert!(CapabilityGatewayHttpConfig::for_principals(vec![
        ("one-token", "agent/one"),
        ("two-token", "agent/two"),
    ])
    .unwrap()
    .with_principal("agent/ambiguous")
    .is_err());

    let multi_debug = format!(
        "{:?}",
        CapabilityGatewayHttpConfig::for_principals(vec![
            ("first-secret", "agent/one"),
            ("second-secret", "agent/two"),
        ])
        .unwrap()
    );
    assert!(multi_debug.contains("[redacted]"));
    assert!(multi_debug.contains("agent/one"));
    assert!(multi_debug.contains("agent/two"));
    assert!(!multi_debug.contains("first-secret"));
    assert!(!multi_debug.contains("second-secret"));
}

#[test]
fn registry_resolver_rejects_a_foreign_cursor_before_opening_provider_state() {
    let descriptor = test_descriptor();
    let registry_installation =
        InstallationId::new(InstallationKind::User, "user/resolver-tests").unwrap();
    let registry = CapabilityRegistry::from_env(registry_installation).unwrap();
    let foreign_installation =
        InstallationId::new(InstallationKind::Workspace, "workspace/resolver-tests").unwrap();
    let cursor = test_cursor(&descriptor, foreign_installation);
    let error = CapabilityGatewayRegistryResolver::new(registry, cursor, Arc::new(NoopFactory))
        .expect_err("a resolver must be installation-bound");
    assert_eq!(error.code, "use.capability.snapshot_scope_mismatch");
}

#[tokio::test]
async fn resolved_provider_holds_one_generation_lease_through_invocation() {
    fn assert_send_sync<T: Send + Sync>() {}
    assert_send_sync::<CapabilityGatewayInvocationLease>();
    assert_send_sync::<CapabilityGatewayResolvedProvider>();

    let descriptor = test_descriptor();
    let expected = descriptor.invocation_ref.clone();
    let active = Arc::new(AtomicUsize::new(0));
    let completed = Arc::new(AtomicUsize::new(0));
    let resolver = Arc::new(LeaseProbeResolver {
        expected,
        resolves: AtomicUsize::new(0),
        active: Arc::clone(&active),
        completed: Arc::clone(&completed),
    });
    let provider = CapabilityGatewayResolvedProvider::new(resolver.clone());
    let context = CapabilityGatewayRequestContext::stdio();

    let result = provider
        .authorize_and_invoke(&descriptor, serde_json::json!({"query": "lease"}), &context)
        .await
        .expect("the resolved invocation should succeed");
    assert_eq!(result["query"], "lease");
    assert_eq!(resolver.resolves.load(Ordering::SeqCst), 1);
    assert_eq!(completed.load(Ordering::SeqCst), 1);
    assert_eq!(active.load(Ordering::SeqCst), 0);
}

#[tokio::test]
async fn resolved_provider_rejects_a_handle_for_a_different_reference() {
    let descriptor = test_descriptor();
    let other = InvocationRef::derive(
        &descriptor.package_id,
        &descriptor.surface,
        descriptor.generation,
        &format!("sha256:{}", "9".repeat(64)),
    )
    .unwrap();
    let resolver = Arc::new(LeaseProbeResolver {
        expected: other,
        resolves: AtomicUsize::new(0),
        active: Arc::new(AtomicUsize::new(0)),
        completed: Arc::new(AtomicUsize::new(0)),
    });
    let provider = CapabilityGatewayResolvedProvider::new(resolver);
    let error = provider
        .invoke(
            &descriptor,
            serde_json::json!({"query": "mismatch"}),
            &CapabilityGatewayRequestContext::stdio(),
        )
        .await
        .expect_err("a resolver must not return a mismatched opaque handle");
    assert_eq!(
        error.code,
        "use.plugin.capability_gateway_resolution_mismatch"
    );
}

#[tokio::test]
async fn adapter_uses_standard_mcp_initialization_list_and_call() {
    let descriptor = test_descriptor();
    let invocation_ref = descriptor.invocation_ref.clone();
    let catalog = test_catalog(descriptor);
    let provider = Arc::new(RecordingProvider::default());
    let server = CapabilityGatewayMcpServer::new(catalog, provider.clone()).unwrap();
    let (server_transport, client_transport) = tokio::io::duplex(64 * 1024);
    let server_handle = tokio::spawn(async move {
        server
            .serve(server_transport)
            .await
            .unwrap()
            .waiting()
            .await
            .unwrap();
    });
    let client = TestClient.serve(client_transport).await.unwrap();

    let tools = client.list_all_tools().await.unwrap();
    assert_eq!(tools.len(), 1);
    assert_eq!(tools[0].name, "search");
    assert_eq!(tools[0].title.as_deref(), Some("Search"));
    assert!(tools[0].output_schema.is_some());
    assert_eq!(
        tools[0].annotations.as_ref().unwrap().read_only_hint,
        Some(true)
    );
    let advertised = serde_json::to_value(&tools[0]).unwrap();
    for private_field in [
        "invocationRef",
        "artifactRef",
        "endpointRef",
        "packageRoot",
        "path",
        "secret",
    ] {
        assert!(
            advertised.get(private_field).is_none(),
            "{private_field} leaked"
        );
    }

    let result = client
        .call_tool(CallToolRequestParam {
            name: "search".into(),
            arguments: Some(
                serde_json::json!({ "query": "mcp" })
                    .as_object()
                    .unwrap()
                    .clone(),
            ),
        })
        .await
        .unwrap();
    assert_eq!(result.is_error, Some(false));
    assert_eq!(
        result
            .structured_content
            .as_ref()
            .and_then(|value| value["arguments"]["query"].as_str()),
        Some("mcp")
    );
    {
        let calls = provider.calls.lock().unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].0, invocation_ref);
        assert_eq!(calls[0].1["query"], "mcp");
        assert_eq!(calls[0].2.transport(), CapabilityGatewayTransport::Stdio);
        assert!(calls[0].2.principal().is_none());
    }
    {
        let authorizations = provider.authorizations.lock().unwrap();
        assert_eq!(authorizations.len(), 1);
        assert_eq!(
            authorizations[0].transport(),
            CapabilityGatewayTransport::Stdio
        );
        assert!(authorizations[0].principal().is_none());
    }

    client.cancel().await.unwrap();
    server_handle.await.unwrap();
}

#[tokio::test]
async fn adapter_exposes_standard_mcp_resources_and_prompts() {
    let tool = test_descriptor();
    let resource = test_resource_descriptor();
    let prompt = test_prompt_descriptor();
    let resource_uri = resource.resource_uri().unwrap().as_str().to_owned();
    let catalog = CapabilityGatewayCatalog::new(
        InstallationId::new(InstallationKind::User, "user/gateway-tests").unwrap(),
        9,
        vec![tool, resource, prompt],
    )
    .unwrap();
    let provider = Arc::new(RecordingProvider::default());
    let server = CapabilityGatewayMcpServer::new(catalog, provider.clone()).unwrap();
    let (server_transport, client_transport) = tokio::io::duplex(64 * 1024);
    let server_handle = tokio::spawn(async move {
        server
            .serve(server_transport)
            .await
            .unwrap()
            .waiting()
            .await
            .unwrap();
    });
    let client = TestClient.serve(client_transport).await.unwrap();

    let resources = client.list_all_resources().await.unwrap();
    assert_eq!(resources.len(), 1);
    assert_eq!(resources[0].uri, resource_uri);
    assert_eq!(resources[0].name, "knowledge");
    assert!(resources[0].uri.starts_with("resource:v1:sha256:"));
    let read = client
        .read_resource(ReadResourceRequestParam {
            uri: resources[0].uri.clone(),
        })
        .await
        .unwrap();
    assert_eq!(read.contents.len(), 1);
    match &read.contents[0] {
        ResourceContents::TextResourceContents { uri, text, .. } => {
            assert_eq!(uri, &resource_uri);
            assert_eq!(text, "verified resource contents");
        }
        ResourceContents::BlobResourceContents { .. } => panic!("expected text resource"),
    }

    let prompts = client.list_all_prompts().await.unwrap();
    assert_eq!(prompts.len(), 1);
    assert_eq!(prompts[0].name, "research");
    assert_eq!(prompts[0].arguments.as_ref().unwrap()[0].name, "topic");
    let prompt = client
        .get_prompt(GetPromptRequestParam {
            name: "research".to_owned(),
            arguments: Some(
                serde_json::json!({ "topic": "mcp" })
                    .as_object()
                    .unwrap()
                    .clone(),
            ),
        })
        .await
        .unwrap();
    assert_eq!(prompt.messages.len(), 1);
    match &prompt.messages[0].content {
        rmcp::model::PromptMessageContent::Text { text } => {
            assert!(text.contains("mcp"));
        }
        _ => panic!("expected text prompt message"),
    }

    assert_eq!(provider.authorizations.lock().unwrap().len(), 2);
    client.cancel().await.unwrap();
    server_handle.await.unwrap();
}

#[tokio::test]
async fn adapter_fails_closed_when_content_provider_is_not_configured() {
    let resource = test_resource_descriptor();
    let prompt = test_prompt_descriptor();
    let resource_uri = resource.resource_uri().unwrap().as_str().to_owned();
    let catalog = CapabilityGatewayCatalog::new(
        InstallationId::new(InstallationKind::User, "user/gateway-tests").unwrap(),
        9,
        vec![resource, prompt],
    )
    .unwrap();
    let server =
        CapabilityGatewayMcpServer::new(catalog, Arc::new(RecordingProviderWithoutContent))
            .unwrap();
    let (server_transport, client_transport) = tokio::io::duplex(64 * 1024);
    let server_handle = tokio::spawn(async move {
        server
            .serve(server_transport)
            .await
            .unwrap()
            .waiting()
            .await
            .unwrap();
    });
    let client = TestClient.serve(client_transport).await.unwrap();
    assert!(client
        .read_resource(ReadResourceRequestParam { uri: resource_uri })
        .await
        .is_err());
    assert!(client
        .get_prompt(GetPromptRequestParam {
            name: "research".to_owned(),
            arguments: Some(
                serde_json::json!({ "topic": "mcp" })
                    .as_object()
                    .unwrap()
                    .clone(),
            ),
        })
        .await
        .is_err());
    client.cancel().await.unwrap();
    server_handle.await.unwrap();
}

#[test]
fn gateway_content_contract_rejects_pathful_resources_and_unknown_prompt_arguments() {
    let resource = test_resource_descriptor();
    let opaque_uri = resource.resource_uri().unwrap().as_str().to_owned();
    assert!(validate_resource_contents(
        &opaque_uri,
        &[ResourceContents::text("private", "file:///srv/private.txt")]
    )
    .is_err());
    let declarations = vec![CapabilityPromptArgument::new("topic", true)];
    assert!(
        validate_prompt_arguments(&serde_json::json!({ "other": "value" }), &declarations).is_err()
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn streamable_http_requires_explicit_auth_origin_and_limits_requests() {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    let shutdown = CancellationToken::new();
    let limits = CapabilityGatewayLimits::new(4, 1, Duration::from_secs(60)).unwrap();
    let config = CapabilityGatewayHttpConfig::new("secret-token")
        .unwrap()
        .with_allowed_origin("https://agent.example")
        .unwrap()
        .with_limits(limits)
        .unwrap();
    let server = CapabilityGatewayMcpServer::new(
        test_catalog(test_descriptor()),
        Arc::new(RecordingProvider::default()),
    )
    .unwrap();
    let server_handle =
        tokio::spawn(server.serve_streamable_http(listener, config, shutdown.clone()));
    tokio::time::sleep(Duration::from_millis(20)).await;

    let unauthorized = raw_gateway_http_response(port, "").await;
    assert!(unauthorized.starts_with("HTTP/1.1 401"));
    let duplicate_authorization = raw_gateway_http_response(
        port,
        "Authorization: Bearer secret-token\r\nAuthorization: Bearer secret-token\r\n",
    )
    .await;
    assert!(duplicate_authorization.starts_with("HTTP/1.1 401"));
    let untrusted_origin = raw_gateway_http_response(
        port,
        "Authorization: Bearer secret-token\r\nOrigin: https://attacker.example\r\n",
    )
    .await;
    assert!(untrusted_origin.starts_with("HTTP/1.1 403"));
    let duplicate_origin = raw_gateway_http_response(
        port,
        "Authorization: Bearer secret-token\r\nOrigin: https://agent.example\r\nOrigin: https://agent.example\r\n",
    )
    .await;
    assert!(duplicate_origin.starts_with("HTTP/1.1 403"));

    let authorized = raw_gateway_http_response(
        port,
        "Authorization: Bearer secret-token\r\nOrigin: https://agent.example\r\n",
    )
    .await;
    assert!(!authorized.starts_with("HTTP/1.1 401"));
    assert!(!authorized.starts_with("HTTP/1.1 403"));

    let limited = raw_gateway_http_response(
        port,
        "Authorization: Bearer secret-token\r\nOrigin: https://agent.example\r\n",
    )
    .await;
    assert!(limited.starts_with("HTTP/1.1 429"));

    shutdown.cancel();
    server_handle.await.unwrap().unwrap();
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn streamable_http_accepts_a_standard_rust_client_without_shared_filesystem() {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    let shutdown = CancellationToken::new();
    let provider = Arc::new(RecordingProvider::default());
    let server =
        CapabilityGatewayMcpServer::new(test_catalog(test_descriptor()), provider.clone()).unwrap();
    let server_handle = tokio::spawn(server.serve_streamable_http(
        listener,
        CapabilityGatewayHttpConfig::for_principal("secret-token", "agent/remote-client").unwrap(),
        shutdown.clone(),
    ));
    tokio::time::sleep(Duration::from_millis(20)).await;

    let transport = StreamableHttpClientTransport::from_config(
        StreamableHttpClientTransportConfig::with_uri(format!("http://127.0.0.1:{port}/mcp"))
            .auth_header("secret-token"),
    );
    let client = TestClient.serve(transport).await.unwrap();
    let tools = client.list_all_tools().await.unwrap();
    assert_eq!(tools.len(), 1);
    assert_eq!(tools[0].name, "search");
    let result = client
        .call_tool(CallToolRequestParam {
            name: "search".into(),
            arguments: Some(
                serde_json::json!({ "query": "remote" })
                    .as_object()
                    .unwrap()
                    .clone(),
            ),
        })
        .await
        .unwrap();
    assert_eq!(result.is_error, Some(false));
    {
        let calls = provider.calls.lock().unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(
            calls[0].2.transport(),
            CapabilityGatewayTransport::StreamableHttp
        );
        assert_eq!(
            calls[0]
                .2
                .principal()
                .map(CapabilityGatewayPrincipal::as_str),
            Some("agent/remote-client")
        );
    }
    {
        let authorizations = provider.authorizations.lock().unwrap();
        assert_eq!(authorizations.len(), 1);
        assert_eq!(
            authorizations[0]
                .principal()
                .map(CapabilityGatewayPrincipal::as_str),
            Some("agent/remote-client")
        );
    }

    client.cancel().await.unwrap();
    shutdown.cancel();
    server_handle.await.unwrap().unwrap();
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn streamable_http_maps_each_bearer_credential_to_its_principal() {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    let shutdown = CancellationToken::new();
    let provider = Arc::new(RecordingProvider::default());
    let config = CapabilityGatewayHttpConfig::for_principals(vec![
        ("alpha-secret", "agent/alpha"),
        ("beta-secret", "agent/beta"),
    ])
    .unwrap();
    let server =
        CapabilityGatewayMcpServer::new(test_catalog(test_descriptor()), provider.clone()).unwrap();
    let server_handle =
        tokio::spawn(server.serve_streamable_http(listener, config, shutdown.clone()));
    tokio::time::sleep(Duration::from_millis(20)).await;

    let alpha_transport = StreamableHttpClientTransport::from_config(
        StreamableHttpClientTransportConfig::with_uri(format!("http://127.0.0.1:{port}/mcp"))
            .auth_header("alpha-secret"),
    );
    let alpha = TestClient.serve(alpha_transport).await.unwrap();
    alpha
        .call_tool(CallToolRequestParam {
            name: "search".into(),
            arguments: Some(
                serde_json::json!({ "query": "alpha" })
                    .as_object()
                    .unwrap()
                    .clone(),
            ),
        })
        .await
        .unwrap();
    alpha.cancel().await.unwrap();

    let beta_transport = StreamableHttpClientTransport::from_config(
        StreamableHttpClientTransportConfig::with_uri(format!("http://127.0.0.1:{port}/mcp"))
            .auth_header("beta-secret"),
    );
    let beta = TestClient.serve(beta_transport).await.unwrap();
    beta.call_tool(CallToolRequestParam {
        name: "search".into(),
        arguments: Some(
            serde_json::json!({ "query": "beta" })
                .as_object()
                .unwrap()
                .clone(),
        ),
    })
    .await
    .unwrap();
    beta.cancel().await.unwrap();

    {
        let calls = provider.calls.lock().unwrap();
        assert_eq!(calls.len(), 2);
        assert_eq!(calls[0].1["query"], "alpha");
        assert_eq!(
            calls[0]
                .2
                .principal()
                .map(CapabilityGatewayPrincipal::as_str),
            Some("agent/alpha")
        );
        assert_eq!(calls[1].1["query"], "beta");
        assert_eq!(
            calls[1]
                .2
                .principal()
                .map(CapabilityGatewayPrincipal::as_str),
            Some("agent/beta")
        );
    }

    shutdown.cancel();
    server_handle.await.unwrap().unwrap();
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn http_principal_reaches_policy_before_invocation() {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    let shutdown = CancellationToken::new();
    let provider = Arc::new(PrincipalPolicyProvider::default());
    let server =
        CapabilityGatewayMcpServer::new(test_catalog(test_descriptor()), provider.clone()).unwrap();
    let server_handle = tokio::spawn(server.serve_streamable_http(
        listener,
        CapabilityGatewayHttpConfig::for_principal("secret-token", "agent/denied").unwrap(),
        shutdown.clone(),
    ));
    tokio::time::sleep(Duration::from_millis(20)).await;

    let transport = StreamableHttpClientTransport::from_config(
        StreamableHttpClientTransportConfig::with_uri(format!("http://127.0.0.1:{port}/mcp"))
            .auth_header("secret-token"),
    );
    let client = TestClient.serve(transport).await.unwrap();
    let result = client
        .call_tool(CallToolRequestParam {
            name: "search".into(),
            arguments: Some(
                serde_json::json!({ "query": "policy" })
                    .as_object()
                    .unwrap()
                    .clone(),
            ),
        })
        .await
        .unwrap();
    assert_eq!(result.is_error, Some(true));
    assert_eq!(
        result.structured_content.as_ref().unwrap()["code"],
        MCP_AUTHORIZATION_ERROR
    );
    assert!(provider.calls.lock().unwrap().is_empty());

    client.cancel().await.unwrap();
    shutdown.cancel();
    server_handle.await.unwrap().unwrap();
}

async fn raw_gateway_http_response(port: u16, headers: &str) -> String {
    let mut stream = tokio::net::TcpStream::connect(("127.0.0.1", port))
        .await
        .unwrap();
    let request = format!(
        "GET /mcp HTTP/1.1\r\nHost: 127.0.0.1:{port}\r\nConnection: close\r\n{headers}\r\n"
    );
    stream.write_all(request.as_bytes()).await.unwrap();
    let mut response = Vec::new();
    stream.read_to_end(&mut response).await.unwrap();
    String::from_utf8(response).unwrap()
}

#[tokio::test]
async fn adapter_rejects_arguments_before_provider_dispatch() {
    let provider = Arc::new(RecordingProvider::default());
    let server =
        CapabilityGatewayMcpServer::new(test_catalog(test_descriptor()), provider.clone()).unwrap();
    let (server_transport, client_transport) = tokio::io::duplex(64 * 1024);
    let server_handle = tokio::spawn(async move {
        server
            .serve(server_transport)
            .await
            .unwrap()
            .waiting()
            .await
            .unwrap();
    });
    let client = TestClient.serve(client_transport).await.unwrap();

    let error = client
        .call_tool(CallToolRequestParam {
            name: "search".into(),
            arguments: Some(
                serde_json::json!({ "query": 42 })
                    .as_object()
                    .unwrap()
                    .clone(),
            ),
        })
        .await
        .expect_err("invalid arguments must be rejected by the MCP boundary");
    assert!(error.to_string().contains("published schema"));
    assert!(provider.calls.lock().unwrap().is_empty());

    client.cancel().await.unwrap();
    server_handle.await.unwrap();
}

#[tokio::test]
async fn adapter_rejects_provider_output_outside_the_published_schema() {
    let server = CapabilityGatewayMcpServer::new(
        test_catalog(test_descriptor()),
        Arc::new(InvalidOutputProvider),
    )
    .unwrap();
    let (server_transport, client_transport) = tokio::io::duplex(64 * 1024);
    let server_handle = tokio::spawn(async move {
        server
            .serve(server_transport)
            .await
            .unwrap()
            .waiting()
            .await
            .unwrap();
    });
    let client = TestClient.serve(client_transport).await.unwrap();

    let result = client
        .call_tool(CallToolRequestParam {
            name: "search".into(),
            arguments: Some(
                serde_json::json!({ "query": "ok" })
                    .as_object()
                    .unwrap()
                    .clone(),
            ),
        })
        .await
        .unwrap();
    assert_eq!(result.is_error, Some(true));
    let error = result.structured_content.expect("structured MCP error");
    assert_eq!(error["code"], MCP_SCHEMA_ERROR);
    assert!(!error.to_string().contains("not-a-boolean"));

    client.cancel().await.unwrap();
    server_handle.await.unwrap();
}

#[tokio::test]
async fn adapter_sanitizes_provider_errors_at_the_agent_boundary() {
    let server =
        CapabilityGatewayMcpServer::new(test_catalog(test_descriptor()), Arc::new(FailingProvider))
            .unwrap();
    let (server_transport, client_transport) = tokio::io::duplex(64 * 1024);
    let server_handle = tokio::spawn(async move {
        server
            .serve(server_transport)
            .await
            .unwrap()
            .waiting()
            .await
            .unwrap();
    });
    let client = TestClient.serve(client_transport).await.unwrap();

    let result = client
        .call_tool(CallToolRequestParam {
            name: "search".into(),
            arguments: Some(
                serde_json::json!({ "query": "ok" })
                    .as_object()
                    .unwrap()
                    .clone(),
            ),
        })
        .await
        .unwrap();
    assert_eq!(result.is_error, Some(true));
    let error = result.structured_content.expect("structured MCP error");
    assert_eq!(error["code"], MCP_INVOCATION_ERROR);
    let serialized = error.to_string();
    assert!(!serialized.contains("private token"));
    assert!(!serialized.contains("/srv/a3s/secrets"));
    assert!(!serialized.contains("provider.internal_secret"));

    client.cancel().await.unwrap();
    server_handle.await.unwrap();
}

#[tokio::test]
async fn adapter_denies_unauthorized_calls_before_provider_dispatch() {
    let provider = Arc::new(DenyingProvider::default());
    let server =
        CapabilityGatewayMcpServer::new(test_catalog(test_descriptor()), provider.clone()).unwrap();
    let (server_transport, client_transport) = tokio::io::duplex(64 * 1024);
    let server_handle = tokio::spawn(async move {
        server
            .serve(server_transport)
            .await
            .unwrap()
            .waiting()
            .await
            .unwrap();
    });
    let client = TestClient.serve(client_transport).await.unwrap();

    let result = client
        .call_tool(CallToolRequestParam {
            name: "search".into(),
            arguments: Some(
                serde_json::json!({ "query": "secret" })
                    .as_object()
                    .unwrap()
                    .clone(),
            ),
        })
        .await
        .unwrap();
    assert_eq!(result.is_error, Some(true));
    let error = result
        .structured_content
        .expect("structured authorization error");
    assert_eq!(error["code"], MCP_AUTHORIZATION_ERROR);
    assert!(!error.to_string().contains("private policy"));
    assert!(provider.calls.lock().unwrap().is_empty());

    client.cancel().await.unwrap();
    server_handle.await.unwrap();
}

#[test]
fn adapter_rejects_a_schema_the_fixed_validator_cannot_compile() {
    let mut descriptor = test_descriptor();
    if let CapabilityDescriptorKind::Tool { input_schema, .. } = &mut descriptor.capability {
        *input_schema = serde_json::json!({
            "type": "object",
            "additionalProperties": false,
            "properties": {"query": {"type": "not-a-json-type"}}
        });
    }
    let error = CapabilityGatewayMcpServer::new(
        test_catalog(descriptor),
        Arc::new(RecordingProvider::default()),
    )
    .expect_err("invalid schemas must not become callable routes");
    assert_eq!(error.code, MCP_ERROR);
    assert!(!error.message.contains("not-a-json-type"));
}

#[test]
fn compiled_schemas_never_resolve_external_resources() {
    let error = CompiledCapabilitySchema::compile(&serde_json::json!({
        "$ref": "https://example.invalid/schema"
    }))
    .expect_err("external schema resources must be rejected");
    assert_eq!(error.code, MCP_ERROR);
    assert!(!error.message.contains("example.invalid"));
}

#[test]
fn adapter_exposes_only_agent_tools_and_is_send_sync() {
    fn assert_send_sync<T: Send + Sync>() {}
    assert_send_sync::<CapabilityGatewayMcpServer>();
    assert_send_sync::<RecordingProvider>();

    let catalog = test_catalog(test_descriptor());
    let provider = Arc::new(RecordingProvider::default());
    let server = CapabilityGatewayMcpServer::new(catalog, provider).unwrap();
    assert_eq!(server.catalog().descriptors().len(), 1);
    assert_eq!(server.tool_router.list_all().len(), 1);
    assert!(server.snapshot_cursor().is_none());
}

#[test]
fn snapshot_binding_requires_exact_package_generation_evidence() {
    let descriptor = test_descriptor();
    let installation = InstallationId::new(InstallationKind::User, "user/gateway-tests").unwrap();
    let cursor = test_cursor(&descriptor, installation.clone());
    let catalog = CapabilityGatewayCatalog::new(
        installation.clone(),
        cursor.generation,
        vec![descriptor.clone()],
    )
    .unwrap();

    validate_snapshot_binding_identity(&catalog, installation.clone(), cursor.generation, &cursor)
        .unwrap();

    let lifecycle_bound_catalog = CapabilityGatewayCatalog::new(
        installation.clone(),
        descriptor.generation,
        vec![descriptor.clone()],
    )
    .unwrap();
    assert_eq!(
        validate_snapshot_binding_identity(
            &lifecycle_bound_catalog,
            installation.clone(),
            cursor.generation,
            &cursor,
        )
        .unwrap_err()
        .code,
        MCP_ERROR
    );

    let mut wrong_generation = cursor.clone();
    wrong_generation.generation += 1;
    assert_eq!(
        validate_snapshot_binding_identity(
            &catalog,
            installation.clone(),
            cursor.generation,
            &wrong_generation,
        )
        .unwrap_err()
        .code,
        MCP_ERROR
    );

    let mut wrong_digest = cursor.clone();
    wrong_digest.packages[0].package_digest = format!("sha256:{}", "f".repeat(64));
    assert_eq!(
        validate_snapshot_binding_identity(
            &catalog,
            installation.clone(),
            cursor.generation,
            &wrong_digest,
        )
        .unwrap_err()
        .code,
        MCP_ERROR
    );

    let mut missing_package = cursor.clone();
    missing_package.packages.clear();
    assert_eq!(
        validate_snapshot_binding_identity(
            &catalog,
            installation,
            cursor.generation,
            &missing_package,
        )
        .unwrap_err()
        .code,
        MCP_ERROR
    );
}

#[test]
fn snapshot_binding_rejects_unleasable_packages() {
    let descriptor = test_descriptor();
    let catalog = test_catalog(descriptor.clone());
    let installation = catalog.installation().clone();
    let mut cursor = test_cursor(&descriptor, installation.clone());
    cursor.unleasable_packages = vec!["acme/other".to_owned()];
    assert_eq!(
        validate_snapshot_binding_identity(&catalog, installation, cursor.generation, &cursor,)
            .unwrap_err()
            .code,
        MCP_ERROR
    );
}

#[cfg(feature = "extensions")]
#[test]
fn leased_server_retains_the_exact_snapshot_across_clones() {
    std::thread::Builder::new()
        .name("capability-gateway-lease".to_owned())
        .stack_size(8 * 1024 * 1024)
        .spawn(|| {
            tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .unwrap()
                .block_on(leased_server_snapshot_lifetime());
        })
        .unwrap()
        .join()
        .unwrap();
}

#[cfg(feature = "extensions")]
async fn leased_server_snapshot_lifetime() {
    let temporary = tempfile::tempdir().unwrap();
    let installation =
        InstallationId::new(InstallationKind::Workspace, "gateway-lease-tests").unwrap();
    let registry = a3s_use_extension::ExtensionRegistry::new(
        a3s_use_extension::ExtensionPaths::new(
            temporary.path().join("data"),
            temporary.path().join("state"),
            installation.clone(),
        )
        .unwrap(),
    );
    let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("crates/extension/fixtures/packages/plugin-v3-cognitive/package");
    let package = a3s_use_extension::ExtensionLifecyclePackage::prepare_local(
        "acme/cognitive",
        &fixture,
        true,
    )
    .await
    .unwrap();
    let identity = a3s_use_extension::ExtensionLifecycleIdentity::new(
        package.package_id(),
        package.package_digest(),
        package.manifest_digest(),
        1,
    )
    .unwrap();
    registry
        .commit_lifecycle_package(&identity, &package)
        .await
        .unwrap();
    registry.publish_lifecycle_package(&identity).await.unwrap();

    let capability_registry = crate::capability_registry::CapabilityRegistry::new(registry);
    let snapshot = capability_registry.snapshot().await.unwrap();
    let package = &snapshot.cursor().packages[0];
    let package_id = package.package_id.clone();
    let lifecycle_generation = package.lifecycle_generation;
    let package_digest = package.package_digest.clone();
    let manifest_digest = package.manifest_digest.clone();
    let mut descriptor = test_descriptor();
    descriptor.package_id = PluginPackageId::parse(package_id).unwrap();
    descriptor.generation = lifecycle_generation;
    descriptor.package_digest = package_digest;
    descriptor.manifest_digest = manifest_digest;
    descriptor.invocation_ref = InvocationRef::derive(
        &descriptor.package_id,
        &descriptor.surface,
        descriptor.generation,
        &format!("sha256:{}", "1".repeat(64)),
    )
    .unwrap();
    descriptor.artifact_ref = Some(
        ArtifactRef::derive(
            &descriptor.package_id,
            &descriptor.surface,
            descriptor.generation,
            &format!("sha256:{}", "2".repeat(64)),
        )
        .unwrap(),
    );
    descriptor.endpoint_ref = Some(
        EndpointRef::derive(
            &descriptor.package_id,
            &descriptor.surface,
            descriptor.generation,
            &format!("sha256:{}", "3".repeat(64)),
        )
        .unwrap(),
    );
    let catalog =
        CapabilityGatewayCatalog::new(installation, snapshot.generation, vec![descriptor]).unwrap();
    let server = CapabilityGatewayMcpServer::from_registry(
        &capability_registry,
        catalog,
        Arc::new(RecordingProvider::default()),
    )
    .await
    .unwrap()
    .expect("published package must be leasable");
    let cursor = server.snapshot_cursor().cloned().unwrap();
    let clone = server.clone();
    drop(server);
    assert_eq!(clone.snapshot_cursor(), Some(&cursor));
}

#[cfg(feature = "extensions")]
#[test]
fn verified_factory_composition_binds_catalog_resolver_and_lease_to_one_cursor() {
    std::thread::Builder::new()
        .name("capability-gateway-composition".to_owned())
        .stack_size(8 * 1024 * 1024)
        .spawn(|| {
            tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .unwrap()
                .block_on(verified_factory_composition_cursor())
        })
        .unwrap()
        .join()
        .unwrap();
}

#[cfg(feature = "extensions")]
async fn verified_factory_composition_cursor() {
    let temporary = tempfile::tempdir().unwrap();
    let installation =
        InstallationId::new(InstallationKind::Workspace, "gateway-composition-tests").unwrap();
    let registry = a3s_use_extension::ExtensionRegistry::new(
        a3s_use_extension::ExtensionPaths::new(
            temporary.path().join("data"),
            temporary.path().join("state"),
            installation.clone(),
        )
        .unwrap(),
    );
    let capability_registry = crate::capability_registry::CapabilityRegistry::new(registry);
    let expected = capability_registry
        .snapshot()
        .await
        .unwrap()
        .cursor()
        .clone();
    let negotiation = CapabilityConsumerNegotiation::generic_mcp();
    let limits = CapabilityGatewayLimits::new(2, 4, Duration::from_secs(30)).unwrap();
    let server =
        CapabilityGatewayMcpServer::from_verified_registry_snapshot_with_factory_and_options(
            &capability_registry,
            Vec::new(),
            Arc::new(NoopFactory),
            CapabilityGatewayCompositionOptions::new(negotiation.clone(), limits),
        )
        .await
        .unwrap()
        .expect("an empty, stable publication must compose");

    assert_eq!(server.snapshot_cursor(), Some(&expected));
    assert_eq!(server.consumer_negotiation(), &negotiation);
    assert!(server.catalog().descriptors().is_empty());
}

fn test_catalog(descriptor: CapabilityDescriptor) -> CapabilityGatewayCatalog {
    CapabilityGatewayCatalog::new(
        InstallationId::new(InstallationKind::User, "user/gateway-tests").unwrap(),
        9,
        vec![descriptor],
    )
    .unwrap()
}

fn test_cursor(
    descriptor: &CapabilityDescriptor,
    installation: InstallationId,
) -> CapabilitySnapshotCursor {
    CapabilitySnapshotCursor {
        schema: CAPABILITY_SNAPSHOT_CURSOR_SCHEMA.to_owned(),
        installation,
        installation_generation: None,
        installation_snapshot_digest: None,
        // The Registry publication generation is independent from the
        // package lifecycle generation carried by each descriptor.
        generation: 9,
        revision: "a".repeat(64),
        registry_revision: format!("sha256:{}", "b".repeat(64)),
        packages: vec![CapabilityPackageGeneration {
            package_id: descriptor.package_id.to_string(),
            lifecycle_generation: descriptor.generation,
            package_digest: descriptor.package_digest.clone(),
            manifest_digest: descriptor.manifest_digest.clone(),
        }],
        unleasable_packages: Vec::new(),
    }
}

fn test_descriptor() -> CapabilityDescriptor {
    let package_id = PluginPackageId::parse("acme/assistant").unwrap();
    let surface = PluginSurfaceRef {
        kind: PluginSurfaceKind::Tool,
        id: "search".to_owned(),
    };
    let digest = |letter: char| format!("sha256:{}", letter.to_string().repeat(64));
    let schema = serde_json::json!({
        "type": "object",
        "additionalProperties": false,
        "properties": { "query": { "type": "string" } },
        "required": ["query"]
    });
    let output_schema = serde_json::json!({
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "arguments": schema.clone(),
            "ok": { "type": "boolean" }
        },
        "required": ["arguments", "ok"]
    });
    CapabilityDescriptor {
        schema: CAPABILITY_DESCRIPTOR_SCHEMA_V1.to_owned(),
        package_id: package_id.clone(),
        surface: surface.clone(),
        generation: 1,
        package_digest: digest('a'),
        manifest_digest: digest('b'),
        title: "Search".to_owned(),
        description: "Search verified knowledge.".to_owned(),
        invocation_ref: InvocationRef::derive(&package_id, &surface, 1, &digest('c')).unwrap(),
        artifact_ref: Some(ArtifactRef::derive(&package_id, &surface, 1, &digest('d')).unwrap()),
        endpoint_ref: Some(EndpointRef::derive(&package_id, &surface, 1, &digest('e')).unwrap()),
        dependencies: Vec::new(),
        publication: CapabilityPublicationEvidence {
            catalog_record_digest: digest('f'),
            signature_digest: digest('0'),
        },
        capability: CapabilityDescriptorKind::Tool {
            name: "search".to_owned(),
            input_schema: schema.clone(),
            output_schema,
            annotations: CapabilityToolAnnotations::new(true, false, true, false),
        },
    }
}

fn test_resource_descriptor() -> CapabilityDescriptor {
    let mut descriptor = test_descriptor();
    let surface = PluginSurfaceRef {
        kind: PluginSurfaceKind::Skill,
        id: "knowledge".to_owned(),
    };
    let digest = |letter: char| format!("sha256:{}", letter.to_string().repeat(64));
    descriptor.surface = surface.clone();
    descriptor.title = "Knowledge".to_owned();
    descriptor.description = "Verified knowledge resource.".to_owned();
    descriptor.invocation_ref = InvocationRef::derive(
        &descriptor.package_id,
        &surface,
        descriptor.generation,
        &digest('c'),
    )
    .unwrap();
    descriptor.artifact_ref = None;
    descriptor.endpoint_ref = None;
    descriptor.capability = CapabilityDescriptorKind::Resource {
        name: "knowledge".to_owned(),
        uri: ResourceRef::derive(
            &descriptor.package_id,
            &surface,
            descriptor.generation,
            &digest('9'),
        )
        .unwrap(),
        mime_type: Some("text/plain".to_owned()),
        size: Some(64),
    };
    descriptor
}

fn test_prompt_descriptor() -> CapabilityDescriptor {
    let mut descriptor = test_descriptor();
    let surface = PluginSurfaceRef {
        kind: PluginSurfaceKind::Skill,
        id: "research".to_owned(),
    };
    let digest = |letter: char| format!("sha256:{}", letter.to_string().repeat(64));
    descriptor.surface = surface.clone();
    descriptor.title = "Research".to_owned();
    descriptor.description = "Research prompt.".to_owned();
    descriptor.invocation_ref = InvocationRef::derive(
        &descriptor.package_id,
        &surface,
        descriptor.generation,
        &digest('8'),
    )
    .unwrap();
    descriptor.artifact_ref = None;
    descriptor.endpoint_ref = None;
    descriptor.capability = CapabilityDescriptorKind::Prompt {
        name: "research".to_owned(),
        arguments: vec![CapabilityPromptArgument::new("topic", true)],
    };
    descriptor
}
